- name: Restart code-server
  ansible.builtin.systemd:
    name: code-server
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode and not (container_mode | default(false))

- name: Restart ttyd
  ansible.builtin.systemd:
    name: ttyd
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode and not (container_mode | default(false))
