- name: Restart code-server
  ansible.builtin.systemd:
    name: code-server
    state: restarted
    daemon_reload: true

- name: Restart ttyd
  ansible.builtin.systemd:
    name: ttyd
    state: restarted
    daemon_reload: true
