target_user: "{{ ansible_user_id }}"
username: mate
dotfiles_repo: "https://github.com/mate-vasarhelyi/infra.git"
timezone: Europe/Budapest
git_email: "{{ vault_git_email }}"
git_user_name: "Mate Vasarhelyi"
github_user: "mate-vasarhelyi"
github_token: "{{ vault_github_token }}"
tailscale_authkey: "{{ vault_tailscale_authkey }}"
user_password: "{{ vault_user_password }}"
claude_oauth_refresh_token: "{{ vault_claude_oauth_refresh_token }}"
jira_api_token: "{{ vault_jira_api_token }}"
jira_server: "{{ vault_jira_server }}"
jira_login: "{{ vault_jira_login }}"
