$ANSIBLE_VAULT;1.1;AES256
63393433616366396538663031313734333961373863326135346132333034373936356266616138
3334656638303865633836373335663061323034333639340a396164653431333830386635653763
32396163356263666330383361613639356339643137313363376639356361306134643137336234
6366393863383631300a633562663437643834346566386234633264363263363161663563616538
65616666303961343263643162393234346135393935633666346639396434663739616538396564
37303462636166396439356538333461303631663337633965393964323030376665326463613434
34316432343562306331633534646431383736346338383536326537656232373536336336343338
36376464396564396538383363613962646563356233666665656233633131326664623766313931
32383134343832653031383539393432616139643731326136353134323765373738626462356462
39646335643333383630373361383934363836323231396135633830303766373534363635613965
39396665613164653734363633386436643165646461626461333463396138323236313266323030
65356133323438396335366130623330383334633566393265366566323831613066333637386130
65623064373230383836346161306337313039353135653863613735366639613030616631353863
66316532653366353739363336313366313832343133393062663536386461643134373631613265
62323336333538386133636465613534333232323836323162633636336338303465343235393738
36643462396331313962366134653639336135666539383538663932336461653864656234666334
61643034623235353935666166363061633431363066396330313534616335613466653335326364
64616234633630636663366161316630663435363331643339363064653433623265656266316338
64373731316237386230633264633038646534393532366635623532336334316238343933326330
35396663343164653064373565326136656162303638663330353136653561366366333536356539
36333439656336353035333235616533376564333234313339613664356334623130393964613731
64326361663639346264386437343838326539626563313939626336333339623565653866636562
34653962626334343131383832376161393633656561323638373730373831323338663039653433
34333030636133626366326661663962333464363964306531656530376162316335633835646638
38636339376633353363363133333035326338326538306339383833613737306436
