$ANSIBLE_VAULT;1.1;AES256
36653436396364306565323734323834653466393630366664626232336262363161613734363065
3836383738666139343534643430373066633065343939300a393834613531613035643661646263
65316336346363396639373834366636636430333463663062653063656134656264353830643433
3964643530663162660a626331376634613532363863353638353634326462343934396137306266
36616236303233313963386336663135326431653835646636373862306430383161663564643866
61363861663132383864313965376164303164626332646564333063333234353163313461353964
39666430393762323339633836386531366462346433663336633233393635626633663961356266
37323866313564666436663661383031356462653961336134636132393566383362613438383832
32383636623664386533613839353738313633376563376531623634343137396134633335343434
6230383538356462323336613639393838333665333261376436
