- name: Install jira-cli from GitHub release
  ansible.builtin.shell: |
    cd /tmp
    curl -fLo jira.tar.gz https://github.com/ankitpokhrel/jira-cli/releases/latest/download/jira_{{ jira_cli_version }}_linux_{{ jira_cli_arch }}.tar.gz
    tar -xzf jira.tar.gz
    install -m 0755 bin/jira /usr/local/bin/jira
    rm -rf jira.tar.gz bin/
  args:
    creates: /usr/local/bin/jira
