- name: Install i3 and dependencies (Arch)
  community.general.pacman:
    name:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - feh
      - xss-lock
      - scrot
      - playerctl
      - polkit-gnome
      - dex
      - xdg-user-dirs
    state: present
