- name: Install passlib (Arch)
  community.general.pacman:
    name: python-passlib
    state: present

- name: Set admin group
  ansible.builtin.set_fact:
    admin_group: wheel

- name: Enable sudo for wheel group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^# ?%wheel ALL=\(ALL:ALL\) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
