- name: Install fprintd
  ansible.builtin.package:
    name:
      - fprintd
      - libfprint
    state: present

- name: Deploy system-auth with fprintd support
  ansible.builtin.copy:
    src: system-auth
    dest: /etc/pam.d/system-auth
    mode: "0644"
    backup: true
