base_packages:
  - curl
  - wget
  - htop
  - jq
  - tree
  - unzip
  - man-db

zellij_version: "0.43.1"

base_packages_archlinux:
  - zellij
  - ripgrep
  - fd
  - bat
  - base-devel
  - github-cli
  - kubectl
  - openssh

base_packages_debian:
  - ripgrep
  - fd-find
  - bat
  - build-essential
  - openssh-client
