- name: Install rofi
  ansible.builtin.package:
    name: rofi
    state: present

- name: Ensure rofi config directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/rofi"
    state: directory
    owner: "{{ username }}"
    mode: "0755"
  become: true
  become_user: "{{ username }}"

- name: Deploy rofi configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.config/rofi/"
    owner: "{{ username }}"
    mode: "0644"
  with_fileglob:
    - "files/*"
  become: true
  become_user: "{{ username }}"
